"""empty message

Revision ID: 066c0e1706fd
Revises: 49e708ba6091
Create Date: 2020-09-26 13:44:09.506386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "066c0e1706fd"
down_revision = "49e708ba6091"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("nickname", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "nickname")
    # ### end Alembic commands ###
