"""empty message

Revision ID: 0f16ec7d9f67
Revises: 066c0e1706fd
Create Date: 2020-09-27 19:12:18.129008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0f16ec7d9f67"
down_revision = "066c0e1706fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("questions_game_id_fkey", "questions", type_="foreignkey")
    op.create_foreign_key(
        None, "questions", "games", ["game_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.create_foreign_key(
        "questions_game_id_fkey", "questions", "games", ["game_id"], ["id"]
    )
    # ### end Alembic commands ###
