"""empty message

Revision ID: 173ac05a965e
Revises: 2cdc9f271df7
Create Date: 2020-09-24 23:27:42.857022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "173ac05a965e"
down_revision = "2cdc9f271df7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("user_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "user_id")
    # ### end Alembic commands ###
