"""empty message

Revision ID: 2cdc9f271df7
Revises: 6ffda3f63113
Create Date: 2020-09-22 19:27:08.113615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2cdc9f271df7"
down_revision = "6ffda3f63113"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("ranked", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "ranked")
    # ### end Alembic commands ###
