"""empty message

Revision ID: 49e708ba6091
Revises: db8e482876cc
Create Date: 2020-09-25 13:12:01.303309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49e708ba6091"
down_revision = "db8e482876cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("user_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "user_id")
    # ### end Alembic commands ###
