"""empty message

Revision ID: 5a210acadd2d
Revises: 6287c880d516
Create Date: 2020-09-03 16:40:49.540284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5a210acadd2d"
down_revision = "6287c880d516"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("end_time", sa.DateTime(), nullable=False))
    op.add_column("games", sa.Column("start_time", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "start_time")
    op.drop_column("games", "end_time")
    # ### end Alembic commands ###
