"""empty message

Revision ID: 6287c880d516
Revises: d52eab91915d
Create Date: 2020-09-03 15:18:46.930612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6287c880d516"
down_revision = "d52eab91915d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("score", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "score")
    # ### end Alembic commands ###
