"""empty message

Revision ID: 6ffda3f63113
Revises: 5a210acadd2d
Create Date: 2020-09-03 16:46:15.492865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6ffda3f63113"
down_revision = "5a210acadd2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "games", "end_time", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "games", "end_time", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
