"""empty message

Revision ID: 7771524ea6b4
Revises: a7b32ae2fdca
Create Date: 2020-08-30 19:06:21.057349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7771524ea6b4"
down_revision = "a7b32ae2fdca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("questions", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("games")
    # ### end Alembic commands ###
