"""empty message

Revision ID: acfb88355ae7
Revises: e8c73cfbef4b
Create Date: 2020-08-31 22:07:24.670800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "acfb88355ae7"
down_revision = "e8c73cfbef4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "options")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column(
            "options",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
