"""empty message

Revision ID: d52eab91915d
Revises: acfb88355ae7
Create Date: 2020-08-31 22:08:19.936476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d52eab91915d"
down_revision = "acfb88355ae7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions", sa.Column("options", sa.ARRAY(sa.String()), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "options")
    # ### end Alembic commands ###
