"""empty message

Revision ID: db8e482876cc
Revises: 173ac05a965e
Create Date: 2020-09-25 13:11:17.232987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "db8e482876cc"
down_revision = "173ac05a965e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "user_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
