"""empty message

Revision ID: ff1123ae20b6
Revises: 7771524ea6b4
Create Date: 2020-08-31 17:50:18.598541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ff1123ae20b6"
down_revision = "7771524ea6b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("options", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("correct_answer", sa.Integer(), nullable=False),
        sa.Column("submitted_answer", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("games", "questions")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column(
            "questions",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("questions")
    # ### end Alembic commands ###
